theme = "catppuccin_mocha"

[editor]
mouse = true
line-number = "absolute"
cursorline = true
color-modes = true
bufferline = "multiple"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

